name: pixels
channels:
  - default
  - conda-forge
dependencies:
  - python=3.9.6
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - python-dotenv
  - conda-forge::ipykernel
  - pip::mplcairo=0.6.1